name: "Build project"

on:
  push:
    branches: [ "main" ]
    paths: 
      - "kotlin/**"
      - ".github/workflows/build-project.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "kotlin/**"
      - ".github/workflows/build-project.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./kotlin

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Cache Konan
      uses: actions/cache@v3
      with:
        path: /home/runner/.konan
        key: konan

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Upload reports
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: reports
        path: ${{ github.workspace }}/kotlin/build/reports
    
