name: "Publish project"

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./kotlin

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Cache Konan
      uses: actions/cache@v3
      with:
          path: /home/runner/.konan
          key: konan

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Publish with Gradle
      env:
        RELEASE_MODE: true
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      run: |
        chmod +x gradlew
        ./gradlew publish

    
